### ISSUE TITLE
TypeError: Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by staticdev** [agronholm/typeguard#145] opened 2020-09-01 22:31 UTC
Hi,

I am having an error on Typeguard that I don't know exactly if it is a bug or missing feature. It looks as if all tests failed and I get this:

```
================================================================================================= ERRORS ==================================================================================================
___________________________________________________________________________________ ERROR collecting tests/test_main.py ___________________________________________________________________________________
tests/test_main.py:8: in <module>
    import git_portfolio.__main__
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/importhook.py:82: in exec_module
    return super().exec_module(module)
.nox/typeguard-3-8/lib/python3.8/site-packages/git_portfolio/__main__.py:56: in <module>
    def checkout(args: Tuple[str]) -> Union[res.ResponseFailure, res.ResponseSuccess]:
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/__init__.py:839: in wrapper
    check_argument_types(memo)
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/__init__.py:700: in check_argument_types
    raise exc from None
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/__init__.py:698: in check_argument_types
    check_type(description, value, expected_type, memo)
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/__init__.py:625: in check_type
    check_typevar(argname, value, expected_type, memo)
.nox/typeguard-3-8/lib/python3.8/site-packages/typeguard/__init__.py:455: in check_typevar
    if not issubclass(value_type, bound_type):
../../.pyenv/versions/3.8.2/lib/python3.8/typing.py:774: in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
E   TypeError: Subscripted generics cannot be used with class and instance checks
--------------------------------------------------------------------------------------------- Captured stdout ---------------------------------------------------------------------------------------------
========================================================================================= short test summary info =========================================================================================
ERROR tests/test_main.py - TypeError: Subscripted generics cannot be used with class and instance checks
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================= 1 error in 1.24s =======================================================================================
```

The output didn't help me a lot and also the error message. The only thing it hinted me is that it related to the generics I added to the code [here](https://github.com/staticdev/git-portfolio/pull/87/files).

**Comment by agronholm** [comment] 2020-09-02 06:01
I think this is due to my misunderstanding of PEP 484: I thought parametrization was not allowed in the bound types of a type variable due to this:

> A type variable may specify an upper bound using bound=<type> (note: <type> itself cannot be parameterized by type variables). This means that an actual type substituted (explicitly or implicitly) for the type variable must be a subtype of the boundary type.

But it really just meant that you can't use other type variables in the generics of the bound types. I actually have unfinished local changes that will ultimately fix this particular issue.

**Comment by agronholm** [comment] 2020-09-02 06:02
Also, this is a duplicate of a recently reported issue (#139).

**Closed by agronholm** 2020-09-02 06:02 UTC
Labels: duplicate
