### ISSUE TITLE
exception message for Union check can be improved.

### ISSUE THREAD

**Issue by yishanhe** [agronholm/typeguard#204] opened 2021-09-23 23:44 UTC
```python
def foo(a: Optional[Dict[int, int]]) -> None:
    pass

typeguard.check_type("a", {1: "2"}, Optional[Dict[int, int]])
```
the error message is 

```
type of a must be one of (Dict, NoneType); got dict instead
```

which doesn't really tell us where is the type mismatch.

**Comment by agronholm** [comment] 2021-10-09 15:31
Duplicate of #65.

**Closed by agronholm** 2021-10-09 15:31 UTC
Labels: duplicate
