### ISSUE TITLE
Only checks the first value instead of the complete list

### ISSUE THREAD

**Issue by cdgaete** [agronholm/typeguard#446] opened 2024-03-27 16:35 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

typeguard-4.2.1

### Python version

Python 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] on linux

### What happened?

I am expeting the TypeCheckError: item 1 of list is not an instance of str

### How can we reproduce the bug?

```python
from typeguard import check_type
from typing import List
string_list = ['nobody', 1, 1, 1, 1]
check_type(string_list, List[str])
```

**Comment by agronholm** [comment] 2024-03-27 19:56
Duplicate of #430, #418 and #417.

**Closed by agronholm** 2024-03-27 19:56 UTC
Labels: bug
