### ISSUE TITLE
Type checking on generic only checks first value entry in data structure 

### ISSUE THREAD

**Issue by teddius** [agronholm/typeguard#418] opened 2023-11-18 11:22 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.5

### Python version

3.10

### What happened?

The function `check_type(value=value, expected_type=expected_type)` only checks the first entry of a Dict / List etc. 

### How can we reproduce the bug?

Reproduce with (pseudo-code) 
`check_type(value={'a': 1, 1: 1}, expected_type=Dict[str, int])` confirms correct type but it is not true for the second entry in the dict. 

Same issue for 
Dict[str, Dict[str, int]]
List[Dict[int, int]]

**Comment by agronholm** [comment] 2023-11-18 13:51
This isn't a bug. Typeguard and Beartype both only check the first element of each collection by default, as checking every element would significantly slow down the application. This can be configured by setting `typeguard.config.collection_check_strategy` to `CollectionCheckStrategy.ALL_ITEMS`.

Where should I document this so people wouldn't send bug reports about this all the time (see https://github.com/agronholm/typeguard/issues/417 for the last one)?

**Comment by DanielYang59** [comment] 2024-02-15 14:56
Sorry @agronholm, I seems to have sent another issue regarding this behaviour in #439. But for some reason the following doesn't trigger an error:
```python
import typeguard
from typeguard import check_type, CollectionCheckStrategy

typeguard.config.collection_check_strategy = CollectionCheckStrategy.ALL_ITEMS
check_type(value=[1, "hi"], expected_type=list[int])
```

**Comment by agronholm** [comment] 2024-03-23 16:36
Closing due to not a bug. I'll think about reverting the default setting in the next major release.

**Closed by agronholm** 2024-03-23 16:36 UTC
Labels: bug
