### ISSUE TITLE
More expressive error message for TypedDict Union

### ISSUE THREAD

**Issue by luk-f-a** [agronholm/typeguard#182] opened 2021-03-22 08:34 UTC
hello, I have started using typeguard and I really like it so far. It's catching so many things that mypy didn't! they complement each other very well. 

**Is your feature request related to a problem? Please describe.**

I'm running typeguard in CI (using the import hooks), and one of the issues when running remotely is that I don't have easy access to a local debugging session. That means that the amount of information that typeguard provides is very important to being able to find what the problem is. Consider this example:

```python
from typeguard import check_argument_types, check_return_type
from typing import TypedDict, Union

class A(TypedDict):
    a: int

class B(A):
    b: int

C = Union[A, B]

def foo(x: C):
    check_argument_types()
    return x

foo({'d':3})

TypeError: type of argument "x" must be one of (A, B); got dict instead
```

This error message does not tell me whether there are extra keys or missing keys in `x`. 

**Describe the solution you'd like**
`TypeError: type of argument "x" must be one of (A, B); got dict instead. extra key(s) ("d") in argument "x". required key(s) ("a") missing from argument "x"`

**Describe alternatives you've considered**
Keeping things are they are. This is acceptable, since there are possible workarounds for the user, but not as convenient as the proposed solution.

**Comment by agronholm** [comment] 2021-03-22 08:36
Duplicate of #65.

**Closed by agronholm** 2021-03-22 08:36 UTC
Labels: enhancement
