### ISSUE TITLE
AttributeError: 'CPUDispatcher' object has no attribute '__globals__' with numba.njit decorated function

### ISSUE THREAD

**Issue by gatoniel** [agronholm/typeguard#277] opened 2022-11-08 12:56 UTC
**Describe the bug**
I am using the `numba.njit` decorator to decorate a function. When I execute `pytest` with typeguard, I get an error when this decorated function is called: `AttributeError: 'CPUDispatcher' object has no attribute '__globals__'`. When trying to narrow down the error and trying to reproduce with a minimal working example, I found out that the error only occurs when the decorated function is imported absolutely from a module. When the same function is imported with a relative import there is no error.

**To Reproduce**
I have three different files: two source files (one for absolute and one for relative import) and one pytest file:
**src/my_module/numba_typeguard.py** (absolute import)
```python
from typing import TypeVar

import numpy as np
import numpy.typing as npt
from numba import njit

T = TypeVar("T", bound=np.generic)


@njit
def numba_sum(
    array: npt.NDArray[T],
) -> T:
    return np.sum(array)
```
**tests/numba_typeguard.py**  (relative import) same function as above but in `tests` directory.
```python
from typing import TypeVar

import numpy as np
import numpy.typing as npt
from numba import njit

T = TypeVar("T", bound=np.generic)


@njit
def numba_sum_local(
    array: npt.NDArray[T],
) -> T:
    return np.sum(array)
```
**tests/test_numba_typeguard.py**
```python
import numpy as np
from my_module.numba_typeguard import numba_sum
from .numba_typeguard import numba_sum_local


def test_numba_sum_njit() -> None:
    x = np.arange(4)
    s = numba_sum(x)
    assert s == np.sum(x)


def test_numba_sum() -> None:
    x = np.arange(4)
    s = numba_sum.py_func(x)
    assert s == np.sum(x)


def test_numba_sum_local_njit() -> None:
    x = np.arange(4)
    s = numba_sum_local(x)
    assert s == np.sum(x)


def test_numba_sum_local() -> None:
    x = np.arange(4)
    s = numba_sum_local.py_func(x)
    assert s == np.sum(x)
```
The following is the error I get:
```
======================================================================================================================================= FAILURES =======================================================================================================================================
_________________________________________________________________________________________________________________________________ test_numba_sum_njit __________________________________________________________________________________________________________________________________

    def test_numba_sum_njit() -> None:
        x = np.arange(4)
>       s = numba_sum(x)

tests/test_numba_typeguard.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.nox/typeguard-3-9/lib/python3.9/site-packages/typeguard/__init__.py:1031: in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <typeguard._CallMemo object at 0x7f9db523c880>, func = CPUDispatcher(<function numba_sum at 0x7f9db52fa5e0>)
frame_locals = {'T': ~T, 'TypeVar': <class 'typing.TypeVar'>, '__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'Asserti...s/.nox/typeguard-3-9/lib/python3.9/site-packages/my_module/__pycache__/numba_typeguard.cpython-39.pyc', ...}
args = (array([0, 1, 2, 3]),), kwargs = {}, forward_refs_policy = <ForwardRefPolicy.ERROR: 1>

    def __init__(self, func: Callable, frame_locals: Optional[Dict[str, Any]] = None,
                 args: tuple = None, kwargs: Dict[str, Any] = None,
                 forward_refs_policy=ForwardRefPolicy.ERROR):
>       super().__init__(func.__globals__, frame_locals)
E       AttributeError: 'CPUDispatcher' object has no attribute '__globals__'

.nox/typeguard-3-9/lib/python3.9/site-packages/typeguard/__init__.py:191: AttributeError
```

**Expected behavior**
I expect the error not to depend on relative vs absolute import.

**Additional context**
As I do not know if this is related to typeguard alone or something else and as I am using the hypermodern python template, I raised also an issue there: https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1271

I tried to remove the `py.typed` file in the src/my_module directory, but this did not resolve the error.

**Comment by agronholm** [comment] 2023-01-10 22:47
I was not able to reproduce the problem on latest master with this code:

from typing import TypeVar

import numpy as np
import numpy.typing as npt
from numba import njit
from typeguard import typechecked

T = TypeVar("T", bound=np.generic)


@typechecked
@njit
def numba_sum(
    array: npt.NDArray[T],
) -> T:
    return np.sum(array)

x = np.arange(4)
s = numba_sum.py_func(x)
Did I do something wrong, or is this no longer an issue?

**Comment by agronholm** [comment] 2023-01-24 16:49
Closing due to a lack of replies.

**Comment by gatoniel** [comment] 2023-01-25 20:31
Sorry for the late response. I installed your latest tag `3.0.0b2` from github and ran the following code:
```python
from typing import TypeVar

import numpy as np
import numpy.typing as npt
from numba import njit
from typeguard import typechecked

T = TypeVar("T", bound=np.generic)


@typechecked
@njit
def numba_sum(
    array: npt.NDArray[T],
) -> T:
    return np.sum(array)

x = np.arange(4)
s = numba_sum.py_func(x)
s = numba_sum(x)
```

It gives me the following error message:
```
Traceback (most recent call last):
  File "/home/niklas/drescherlab/merge-stardist-masks/test.py", line 21, in <module>
    s = numba_sum(x)
  File "/home/niklas/.cache/pypoetry/virtualenvs/merge-stardist-masks-Mk5qjuGF-py3.9/lib/python3.9/site-packages/typeguard/__init__.py", line 286, in wrapper
    memo = CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "/home/niklas/.cache/pypoetry/virtualenvs/merge-stardist-masks-Mk5qjuGF-py3.9/lib/python3.9/site-packages/typeguard/_memo.py", line 54, in __init__
    super().__init__(func.__globals__, frame_locals, config)
AttributeError: 'CPUDispatcher' object has no attribute '__globals__'
```
The problem is not with the `.py_func` but with the real `njitted` function.

**Comment by agronholm** [comment] 2023-01-25 20:49
Not sure what I did before, but I can reproduce this locally now.

**Comment by agronholm** [comment] 2023-01-25 20:50
I am currently in the process of heavily refactoring `@typechecked` now. I'll try this again when that's done.

**Comment by gatoniel** [comment] 2023-01-25 20:51
Thank you so much for looking into this...

Before, you only executed `numba_sum.py_func(x)` not `numba_sum(x)`...

**Comment by agronholm** [comment] 2023-01-25 20:52
> Thank you so much for looking into this...
> 
> Before, you only executed `numba_sum.py_func(x)` not `numba_sum(x)`...

That would explain it :smile:

**Comment by agronholm** [comment] 2023-01-25 21:00
The underlying problem is that `inspect.unwrap()` stops at the `CPUDispatcher` object. If I fix that, I get: `typeguard.TypeCheckError: the return value is not an instance of numpy.generic`. Is this what you expected?

**Comment by agronholm** [comment] 2023-01-25 21:02
Oh and BTW, it didn't work at all on Pythons older than 3.9.

**Closed** 2023-01-25 21:15 UTC
Labels: needs more info
