### ISSUE TITLE
Support common usage of Optional.

### ISSUE THREAD

**Issue by tot0** [agronholm/typeguard#51] opened 2018-10-25 17:53 UTC
It seems, at least in my experience, that a common pattern for Optional arguments is to provide a default value of `None` and then, optionally, add the `Optional[]` qualifier. This results in the expected type of the argument being `Union[some_type, None]`. This can result in a weird `TypeError` though due to the way `Union` is handled for type checking. For example:

```python
@typechecked
def func(arg: Optional[List[str]] = None):
    pass
```
This function if used like this:
```python
func(['value', None])
```
results in this `TypeError`:
```python
TypeError: type of argument "arg" must be one of (List, NoneType); got list instead
```
This doesn't really indicate the actual reason this passed list doesn't match the type requirements of func.

Given this pattern of having the actual expected type, or None indicating it was not passed, seems common I propose special casing the handling of `Union[some_type, None]`. The actual value of the argument can be checked against `None` and if it isn't None then the proper type check against `some_type` is performed. Otherwise if it is `None`, then no further checking needs to happen.

**Comment by fakuivan** [comment] 2018-11-08 19:14
You are passing ``List[Optional[int]]`` to the function, instead of ``Optional[List[str]]``. Something of type ``List[Optional[int]]`` would be ``[1, None]``, as you mentioned, but the function is expecting ``[1, 2]`` OR ``None`` itself.

**Comment by agronholm** [comment] 2019-05-19 12:08
Fixing this will require a total rewrite of typeguard's error reporting logic.

**Comment by agronholm** [comment] 2019-07-14 10:16
Closing in favor of #65 which is the root cause.

**Closed by agronholm** 2019-07-14 10:16 UTC
