### ISSUE TITLE
Please release latest versions to ubuntu

### ISSUE THREAD

**Issue by InigoMoreno** [agronholm/typeguard#270] opened 2022-09-01 10:19 UTC
Hey, I can see that typeguard on ubuntu is still on version 2.2. 
```
$ apt-cache madison python3-typeguard
python3-typeguard |    2.2.2-1 | http://es.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
python3-typeguard |    2.2.2-1 | http://es.archive.ubuntu.com/ubuntu focal/universe i386 Packages
```
Would it be possible to make a new release for the latest version?

**Comment by agronholm** [comment] 2022-09-01 10:20
Duplicate of #257.

**Closed by agronholm** 2022-09-01 10:20 UTC
Labels: enhancement

**Comment by agronholm** [comment] 2022-09-01 10:24
If you were asking about 2.13 being released, then you should ask those maintaining the Ubuntu package. That is not me.

**Comment by InigoMoreno** [comment] 2022-09-01 10:35
Who would that be?

**Comment by agronholm** [comment] 2022-09-01 10:38
Best I could find is "Ubuntu MOTU Developers" (ubuntu-motu@lists.ubuntu.com). I am in no way involved in that, so I don't know any more than you do.
