### ISSUE TITLE
Optional[Union[str, date, datetime]] doesn't work if argument passed in 

### ISSUE THREAD

**Issue by ztane** [agronholm/typeguard#22] opened 2017-09-04 10:55 UTC
The union bug manifests itself if the union is optional.

**Comment by ztane** [comment] 2017-09-04 10:58
Easy to circumvent with `Union[str, date, datetime, None]`, but it still annoys me :D

**Comment by agronholm** [comment] 2017-09-04 11:04
I would probably write it like `Union[str, date, None]` myself (as `datetime` is a subclass of `date` anyway), and it's shorter to write than using `Optional[...]`. But yes, this should not be happening.

**Comment by agronholm** [comment] 2017-09-04 17:18
Cannot reproduce with Python 3.6.2. Please confirm.

**Comment by Stewori** [comment] 2017-09-04 22:23
Is there concrete code to reproduce?

**Comment by ztane** [comment] 2017-09-05 19:41
This was a heisenbug on colleague's computer caused by 3.5.2 + backports.typing 1.2. `backports.typing` injects its crappy types into `typing`. Surprisingly there is *another* kind of trace with 3.5.3 + 1.2.

**Comment by ztane** [comment] 2017-09-05 19:43
Here's the run

```Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from typeguard import typechecked
>>> from typing import Union
>>> @typechecked
... def foo(bar: Union[int, float]):
...     pass
... 
>>> foo(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ztane/ve35/lib/python3.5/site-packages/typeguard.py", line 458, in wrapper
    check_argument_types(memo)
  File "/home/ztane/ve35/lib/python3.5/site-packages/typeguard.py", line 427, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/home/ztane/ve35/lib/python3.5/site-packages/typeguard.py", line 387, in check_type
    if not isinstance(value, expected_type):
  File "/usr/lib/python3.5/typing.py", line 563, in __instancecheck__
    raise TypeError("Unions cannot be used with isinstance().")
TypeError: Unions cannot be used with isinstance().
```

**Comment by agronholm** [comment] 2017-09-05 21:15
I'm not entirely sure if we can reasonably do anything about the backports.typing FUBAR.

**Comment by agronholm** [comment] 2017-09-05 21:35
Ok, I see what's happening here: typeguard tries to import the typing stuff from `backports.typing`, and since that succeeds, it won't import `typing`. Thus the generics from `typing` will not get added to `origin_type_checkers` and thus are subjected to `isinstance()`. So this looks like a fixable problem after all.

**Comment by agronholm** [comment] 2017-11-18 14:10
This has become a moot point now that `backports.typing` is gone from PyPI. Closing.

**Closed by agronholm** 2017-11-18 14:10 UTC
Labels: bug
