### ISSUE TITLE
typechecked Tuple type invalid type check

### ISSUE THREAD

**Issue by GiovanniCardamone** [agronholm/typeguard#53] opened 2018-12-06 08:55 UTC
typeguard==2.2.2

Using `@typechecked` as decorator from a class i'm trying to pass a string, or a Tuple[str].

i defined my type in this way:
```
DocPath = Optional[Union[str, Tuple[str]]]
```

and the signature of my function is this:
```
@typechecked
def path (self, path: Union[DocPath, AnotherTypeWhereICanExtractThePath] = undefined):
```

but running this method with a tuple as parameter for path, cause TypeError Exception.

```
  File "/home/step/Workspace/XXX/.venv/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "path" must be one of (str, Tuple, NoneType); got tuple instead
```

Not sure if is a bug, or i am trying to mix too many types

**Comment by GiovanniCardamone** [comment] 2018-12-06 08:57
sorry i was replacing real Type Name with `AnotherTypeWhereICanExtractThePath` and i forgot to put it back in the traceback:

```
File "/home/step/Workspace/XXX/.venv/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "path" must be one of (str, Tuple, NoneType, AnotherTypeWhereICanExtractThePath); got tuple instead
```

**Comment by agronholm** [comment] 2018-12-06 14:49
Would you mind posting a minimal, fully reproduceable example to make it easier for me to investigate? Thanks!

**Comment by agronholm** [comment] 2019-05-19 11:52
Closing since the requested example code has not materialized in 6 months.

**Closed by agronholm** 2019-05-19 11:52 UTC
