### ISSUE TITLE
Code coverage drop via typeguard 4.0

### ISSUE THREAD

**Issue by alexander-held** [agronholm/typeguard#356] opened 2023-05-12 22:14 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0

### Python version

3.9.16

### What happened?

`typeguard` 4.0 used within `pytest` seems to result in decreases in code coverage when that is calculated simultaneously via `pytest`. I ran into a few examples in https://github.com/scikit-hep/cabinetry/pull/406, below is a reproducer. `typeguard` 3.0.2 is also affected, while `2.13.3` seems not to be.

Here are the relevant library versions I am currently using:
```
coverage                      7.2.5
pytest                        7.3.1
pytest-cov                    4.0.0
typeguard                     4.0.0
```

I am not sure if this is necessarily something wrong with `typeguard` or potentially some interaction with the coverage calculation that just happened to work by chance in the past and no longer does. Happy to provide any additional information that might be useful!

### How can we reproduce the bug?

`foo.py`:
```python
def bar(x: bool) -> None:
    if x:
        pass
    pass
```

`test_foo.py`:
```python
from foo import bar

def test_bar():
    bar(True)
    bar(False)
```

using `typeguard-packages`:
```bash
$ pytest test_foo.py --cov=foo --typeguard-packages foo
================================================= test session starts ==================================================
platform darwin -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: [...]
plugins: cov-4.0.0, anyio-3.6.2, typeguard-4.0.0
collected 1 item

test_foo.py .                                                                                                    [100%]

---------- coverage: platform darwin, python 3.9.16-final-0 ----------
Name     Stmts   Miss  Cover
----------------------------
foo.py       3      1    67%
----------------------------
TOTAL        3      1    67%


================================================== 1 passed in 0.02s ===================================================
```

without `typeguard-packages`:
```bash
$ pytest test_foo.py --cov=foo
================================================= test session starts ==================================================
platform darwin -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: [...]
plugins: cov-4.0.0, anyio-3.6.2, typeguard-4.0.0
collected 1 item

test_foo.py .                                                                                                    [100%]

---------- coverage: platform darwin, python 3.9.16-final-0 ----------
Name     Stmts   Miss  Cover
----------------------------
foo.py       3      0   100%
----------------------------
TOTAL        3      0   100%


================================================== 1 passed in 0.01s ===================================================
```

**Comment by agronholm** [comment] 2023-05-12 22:15
This might be caused by the AST manipulation and recompilation done by Typeguard.

**Comment by agronholm** [comment] 2023-05-12 23:44
If there's something I can do to alleviate this, let me know. But I'm probably not going to investigate on my own.

**Comment by alexander-held** [comment] 2023-05-15 15:53
Thanks! I mostly wanted to ensure with this issue that this is not totally unexpected and to provide something for others to find if they see the same behavior. Luckily this can be worked around relatively easily by splitting coverage and runtime type testing into independent `pytest` runs. I don't really have relevant expertise here, so I'm also unlikely to look more into this myself any time soon.

**Comment by agronholm** [comment] 2023-05-15 15:55
It's possible there could be a solution to this, but I don't really know how coverage and typeguard interact with each other. The solution you described sounds perfectly fine.

**Comment by agronholm** [comment] 2023-08-17 21:31
I'm going to close this, as it's a compatibility issue and not a bug per se. If someone comes up with a solution, it should be created as an enhancement request.

**Closed by agronholm** 2023-08-17 21:31 UTC
Labels: bug
