### ISSUE TITLE
Property with int return type causes error

### ISSUE THREAD

**Issue by HJDCampbell** [agronholm/typeguard#318] opened 2023-03-16 15:08 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.1

### Python version

3.10

### What happened?

Thanks for updating Typeguard, though unfortunately, version 3.0.1 causes an error in my code. I've reduced the error down to the example below, which is hopefully self-explanatory!

### How can we reproduce the bug?

This code:
```python
from typeguard import typechecked


@typechecked
class foo:
    @property
    def fub(self) -> int:
        return 5

a = foo()
print(a.fub)
```
Causes the traceback:
```
C:\Users\Hamish\Git\msm\.venv310\Scripts\python.exe C:\Users\Hamish\Git\msm\msm\typeguardtest.py 
Traceback (most recent call last):
  File "C:\Users\Hamish\Git\msm\msm\typeguardtest.py", line 11, in <module>
    print(a.fub)
  File "C:\Users\Hamish\Git\msm\msm\typeguardtest.py", line 7, in fub
    def fub(self) -> int:
  File "C:\Users\Hamish\Git\msm\.venv310\lib\site-packages\typeguard\_memo.py", line 70, in __init__
    self.type_hints = _type_hints_map[func]
  File "C:\Users\Hamish\AppData\Local\Programs\Python\Python310\lib\weakref.py", line 416, in __getitem__
    return self.data[ref(key)]
TypeError: cannot create weak reference to 'property' object

Process finished with exit code 1
```
I'm expecting this code to run without any error (and print 5).

Please let me know if you'd like any more information, and thank you for maintaining this package!

**Comment by agronholm** [comment] 2023-03-16 15:22
Yeah, if you remove the annotation, the method doesn't get instrumented since there would be nothing to check for.

**Comment by agronholm** [comment] 2023-03-18 12:53
The root cause for this is the same as in #315: typeguard's inability to obtain the original function instance to retrieve the correct type hints. I have a fix in the works that bypasses the issue by duplicating the type annotations in the function body.

**Comment by agronholm** [comment] 2023-03-19 19:29
Would you mind trying the `4.0-dev` branch? Your snippet at least works properly with that.

**Comment by corwinjoy** [comment] 2023-03-21 23:33
I actually ran into a similar problem with setters. I have a class that defines an args property like:
```
    @property
    def _args(self) -> Tuple[Union[torch.Tensor, "LinearOperator", int], ...]:
        return self._args_memo

    @_args.setter
    def _args(self, args: Tuple[Union[torch.Tensor, "LinearOperator", int], ...]) -> None:
        self._args_memo = args
```

and then in the class init method I have
```
   def __init__(self, *args, **kwargs):
        self._args = args
```

typeguard throws a spurious error on `self._args = args` because it mistakenly call the getter version of the property rather than the setter. This worked fine under the old version so I think it may be related.

**Comment by corwinjoy** [comment] 2023-03-21 23:42
The above produces a stack trace like that shown below, but it's just a fancy way of saying that the wrapper is trying to invoke the getter function instead of the setter.
```
../linear_operator/operators/_linear_operator.py:152: in __init__
    self._args = args
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <decorator>
args = (<linear_operator.operators.dense_linear_operator.DenseLinearOperator object at 0x7f6124c47730>, (tensor([[ 1.5693, -0...7],
        [ 0.1743, -0.2726,  1.3835, -0.2421],
        [-0.3467,  0.2257, -0.2421,  1.5709]], requires_grad=True),))
kwargs = {}, memo_stack = []
fn = <function LinearOperator._args at 0x7f6124613910>

E           TypeError: LinearOperator._args() takes 1 positional argument but 2 were given
```

**Comment by agronholm** [comment] 2023-03-22 08:36
That was fixed in 835fb6598cbd61f45a566bec9b042aca7e1db42b but not part of a release yet. I discovered two other problem with local variable assignments, where iterable unpacking (`x, *y = ...)` gave incorrect results. I plan to make another patch release once this has been handled.

**Comment by agronholm** [comment] 2023-03-30 13:20
Yes, this was already reported by the original poster, and is already fixed in the `4.0-dev` branch. Do you have something to  add?

**Comment by jedie** [comment] 2023-03-30 13:26
I tried it now, but it's complete broken, i get this error:

```
ImportError: cannot import name 'CallMemo' from 'typeguard' (/home/jens/toniecloud/bx_py_utils/.venv/lib/python3.10/site-packages/typeguard/__init__.py)
```

**Comment by agronholm** [comment] 2023-03-30 13:32
What's importing `CallMemo`? There is no mention of that in the entire typeguard codebase in `4.0-dev`.

**Comment by jedie** [comment] 2023-03-30 14:45
Good questions. `CallMemo` is not in our code base. I find it only in typeguard:

![image](https://user-images.githubusercontent.com/71315/228873985-61f20b6f-421a-4f11-b875-81e3eadb8c82.png)

**Comment by agronholm** [comment] 2023-03-30 15:02
You're using the wrong branch or revision. CallMemo was entirely removed in a66d1704.

**Comment by AckslD** [comment] 2023-03-30 17:59
Try removing any `.pyc`, I had a similar issue

**Comment by agronholm** [comment] 2023-03-30 18:08
But if leftover .pyc files are the issue, where is the source code that shows `CallMemo` is coming from?

**Comment by AckslD** [comment] 2023-03-30 18:19
Sorry, but I'm not sure I can say. But when I had the OPs issue I tried downgrading to `typeguard<3.0.0` but then got the error re `CallMemo`. I was then very confused since after grepping for `CallMemo` I couldn't find any source code importing it. However after clearing any `.pyc` files the issue went away.

**Comment by agronholm** [comment] 2023-03-30 18:24
At any rate, when upgrading Typeguard, clearing any `-typeguard.pyc` files is a good idea.

**Comment by agronholm** [comment] 2023-04-01 22:12
FYI: 4.0.0rc1 is out. I will likely update the .pyc suffix to `-typeguard400` or similar once the final release is out. Until then, continue to clear the .pyc files when you update.

**Closed by agronholm** 2023-04-01 22:12 UTC
Labels: bug
