### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by animalmutch** [agronholm/typeguard#151] opened 2020-10-14 10:22 UTC
Hi. Great library, thanks! I've just come across a small issue that led me astray for a bit, so thought I should report it. Running the following code gives the error message

> TypeError: type of the return value must be one of (Dict, NoneType); got dict instead

`from typeguard import typechecked
from typing import Optional, Dict

@typechecked
def testTypeguard() -> Optional[Dict[str, int]]:
    return {'a': 'dictionary'}

testTypeguard()`

This is very confusing, since a dict is a Dict, and what's really happening is just that the value is of the wrong type (str instead of int). A different error message in this situation would be really helpful.

Thanks

**Comment by agronholm** [comment] 2020-10-14 10:23
Duplicate of #65.

**Closed by agronholm** 2020-10-14 10:23 UTC
Labels: duplicate
