### ISSUE TITLE
Why does the protocol check enforce that instance methods cannot have mandatory keyword-only arguments?

### ISSUE THREAD

**Issue by mrgrain** [agronholm/typeguard#495] opened 2024-10-11 12:03 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.3.0

### Python version

3.12.0

### What happened?

v4.3.0 added extended checks for Protocols via this [commit](https://github.com/agronholm/typeguard/commit/241d120de7d5e724a9dac10f529318273738a21f#diff-0ac00416d20efb96e963a903c7c8f8e7a5070064af5b4673ad441c7e3114265eR727) (no PR for some reason).

Part of this change is to check methods with `check_callable`. This check enforces that the callable cannot have mandatory keyword-only arguments in its declaration (= keyword-only arguments without default values). However [PEP3102](https://peps.python.org/pep-3102/) seems to explicitly allow keyword-only arguments without defaults.

I suspect this issue might effect all callable, but for us it now surfaced for protocols.

My question/ask is if someone can provide more background information on why this rule is enforced and how it relates to my understanding of PEP3102.

If this is unintentional, we should fix it.

### How can we reproduce the bug?

```python
import typeguard
import typing_extensions

class IFoo(typing_extensions.Protocol):
    def bar(self, *, baz: str) -> None:
        pass
    
class Foo(IFoo):
    def bar(self, *, baz: str) -> None:
        pass

typeguard.check_type(value=Foo(), expected_type=IFoo, collection_check_strategy=typeguard.CollectionCheckStrategy.ALL_ITEMS)    
```

**Comment by agronholm** [comment] 2024-10-26 21:47
The underlying reason was that I was shoehorning these checks into `Callable[]` checks which don't support the notion of keyword-only arguments. I have a fix incoming which adds proper (in theory) method signature checking.

**Comment by agronholm** [comment] 2024-10-26 21:49
This is essentially a duplicate of #465, so I'm closing this one in its favor.

**Closed by agronholm** 2024-10-26 21:49 UTC
Labels: bug

**Comment by mrgrain** [comment] 2024-10-26 22:15
Thank you. Appreciate the response. 👍
