### ISSUE TITLE
Issues with PyCharm debugger

### ISSUE THREAD

**Issue by i3v** [agronholm/typeguard#26] opened 2017-11-17 11:28 UTC
The following simple example fail with recent PyCharm versions:
```
from typeguard import check_argument_types


def run(x: int):
    assert check_argument_types()
    print(x)      # <--- place a breakpoint here and run debug


if __name__ == "__main__":
    run(1)
    # run(1.0)    # uncomment & run normally to make sure it correctly detects incorrect type
  }
}
```
The error message I get is 

```
C:\ProgramFiles\Anaconda\envs\general_py36\python.exe "C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 55659 --file W:/tests/PyTests/typeguard_in_debug/check_args_in_debug.py
pydev debugger: process 18164 is connecting

Connected to pydev debugger (build 172.3968.37)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "W:/tests/PyTests/typeguard_in_debug/check_args_in_debug.py", line 10, in <module>
    run(1)
  File "W:/tests/PyTests/typeguard_in_debug/check_args_in_debug.py", line 5, in run
    assert check_argument_types()
  File "C:\ProgramFiles\Anaconda\envs\general_py36\lib\site-packages\typeguard.py", line 421, in check_argument_types
    memo = _CallMemo(func, frame)
  File "C:\ProgramFiles\Anaconda\envs\general_py36\lib\site-packages\typeguard.py", line 46, in __init__
    self.func_name = function_name(func)
  File "C:\ProgramFiles\Anaconda\envs\general_py36\lib\site-packages\typeguard.py", line 130, in function_name
    module = func.__module__
AttributeError: 'NoneType' object has no attribute '__module__'

Process finished with exit code 1
```
I've already [reported](https://youtrack.jetbrains.com/issue/PY-26612) it on their bug tracker.
Luckily, they've left an option to fallback to the previous debugger mechanism (the `PYDEVD_USE_FRAME_EVAL` trick).

I'd like to report this here as well, just in case. I've still not looked into the code and I'm not sure whether or not it is possible to modify typeguard code so that it would work with JetBrains' debugger.

**Comment by agronholm** [comment] 2017-11-17 11:34
I will try to figure out a fix. But in case typeguard cannot determine the function to check, should I just make the check a no-op?

**Comment by i3v** [comment] 2017-11-17 18:20
I think that if something would "just work" during debug but fail during normal run - it might be very misleading in some cases. Probably, some kind of warning would be better. Maybe with a custom `category`, so that one could easily `filterwarnings` if they would get too noisy?

**Comment by agronholm** [comment] 2018-07-19 13:22
I tried with the latest PyCharm and could not reproduce this, so I'm closing the issue.

**Comment by i3v** [comment] 2018-07-21 00:48
@agronholm, that's weird. Especially if you were able to to reproduce it before. The issue is still there for me. I've just tested the following combinations:

python | typeguard | PyCharm ver
-- | -- | --
3.6.4 | 2.1.3 | 2018.1
3.6.4 | 2.1.3 | 2018.1.1
3.6.4 | 2.1.3 | 2018.1.2
3.6.4 | 2.1.3 | 2018.1.3
3.6.4 | 2.1.3 | 2018.1.4
3.6.4 | 2.1.3 | 2018.2 RC (182.3684.6)
3.6.4 | 2.1.3 | 2018.2 RC (182.3684.58)
3.6.4 | 2.1.4 | 2018.2 RC (182.3684.58)
3.6.4 | 2.2.0 | 2018.2 RC (182.3684.58)
3.6.6 | 2.2.0 | 2018.2 RC (182.3684.58)



(Windows 7 x64)

My env is:
```
name: typeguard_issue26_env

dependencies:
  - python=3.6.6
  - pip:
    - typeguard==2.2.0

# To install:
# conda env create --file=typeguard_issue26_env.yml
```

**Comment by agronholm** [comment] 2018-07-22 14:46
I haven't been able to reproduce this ever. I also didn't notice that Conda was involved. Can you reproduce this with the official Python distribution?

**Comment by i3v** [comment] 2018-07-22 17:47
Yep. Just tested on another PC. 
```
PyCharm 2018.1.4 (Professional Edition) Build #PY-181.5087.37, built on May 24, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
Freshly installed [Python 3.6.6](https://www.python.org/downloads/release/python-366/). And I only did
```
python -m pip install --upgrade pip
python -m pip install typeguard
```
nothing else. And the result is the same.

I was also able to reproduce this with a freshly installed [CentOS-7-x86_64-DVD-1804](https://wiki.centos.org/Download) with Anaconda-5.2.0. And... this time I've noticed that the issue is not present untill I accept [Python Debugger Extension](https://www.jetbrains.com/help/pycharm/cython-speedups.html) install.
Maybe that's the thing? Had you tried to install it?

If you're still unable to reproduce it - maybe I can just share that VM (Oracle Virtualbox)?

**Comment by agronholm** [comment] 2018-07-22 18:03
Ah, I had not tried to install the debugger extension. I will try again with that.

**Comment by agronholm** [comment] 2018-07-22 18:16
I was able to reproduce the problem with the debugger extension installed.

**Closed** 2018-07-22 18:36 UTC

**Comment by agronholm** [comment] 2018-07-22 18:37
The best I can do in that situation is to gracefully skip the type check, which is how I just changed typeguard.

**Comment by i3v** [comment] 2018-07-22 18:54
Thanks! 
I've just added a note on JetBrains' bug tracker that there's no error since that commit, but the underlying issue is still there.

**Comment by alopolska2018** [comment] 2020-12-25 14:49
This actually also occurs with last version of pycharm for linux, all you need to do is replace plugin python-ce with the latest aviable from their webside just go to plugins folder overwrite catalogues and restart pycharm.
