### ISSUE TITLE
Poor error message checking str in Optional[List[str]]

### ISSUE THREAD

**Issue by benclifford** [agronholm/typeguard#197] opened 2021-07-24 14:14 UTC
**Describe the bug**

```
from typeguard import typechecked
from typing import List, Optional

@typechecked
def f(x: Optional[List[str]]):
  return None

f([7])
```

gives this error message:

```
TypeError: type of argument "x" must be one of (List, NoneType); got list instead
```

which does not lead the user to the actual type error that 7 is not a `str`, and complains that it was expecting a list but was given a list.

When annotating f without the Optional wrapper, a much nicer error is returned.

```
from typeguard import typechecked
from typing import List, Optional

@typechecked
def f(x: List[str]):
  return None

f([7])
```

```
TypeError: type of argument "x"[0] must be str; got int instead
```

**To Reproduce**
as above

**Expected behavior**
The nice error message above should appear instead of the confusing one.

**Additional context**
The actual case I'm seeing this is with a more complicated `executors: Union[List[str], Literal['all']]` in https://github.com/parsl/parsl

I've tried two typeguard versions: 2.12.1 and commit 89c1478bd33bcf9a7cccc2c962ebeaa034e51908

```
$ python --version
Python 3.9.2
```

**Comment by agronholm** [comment] 2021-07-24 16:02
Duplicate of #65.

**Closed by agronholm** 2021-07-24 16:02 UTC
Labels: duplicate
